package dataStructure.LinkedList;

public class Main {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		LinkedList ll = new LinkedList(11);
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();

//		System.out.println("remove first : "+ll.removeFirst().value);
//		ll.printList();
//		ll.getHead();
//		ll.getTail();
//		ll.getLength();
//		System.out.println("remove last : "+ll.removeLast().value);
//		ll.printList();
//		ll.getHead();
//		ll.getTail();
//		ll.getLength();

		ll.append(12);
		ll.append(13);
		ll.append(14);
		ll.append(15);
		ll.append(16);
		ll.append(17);
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		System.out.println("**********prepend*************");
		ll.prepend(10);
		ll.prepend(9);
		ll.prepend(8);
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		System.out.println("remove first : " + ll.removeFirst().value);
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		System.out.println("remove last : " + ll.removeLast().value);
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		System.out.println("At -3 : " + (ll.get(-3) != null ? ll.get(-3).value : null));
		System.out.println("At 13 : " + (ll.get(13) != null ? ll.get(13).value : null));
		System.out.println("At 8 : " + (ll.get(8) != null ? ll.get(8).value : null));
		System.out.println("At 7 : " + (ll.get(7) != null ? ll.get(7).value : null));
		System.out.println("At 0 : " + (ll.get(0) != null ? ll.get(0).value : null));
		System.out.println("At 4 : " + (ll.get(4) != null ? ll.get(4).value : null));
		System.out.println("At 3 : " + (ll.get(3) != null ? ll.get(3).value : null));
		System.out.println("At 5 : " + (ll.get(5) != null ? ll.get(5).value : null));
		System.out.println(ll.set(-3, 3));
		System.out.println(ll.set(13, 13));
		System.out.println(ll.set(8, 8));
		System.out.println(ll.set(7, 7));
		System.out.println(ll.set(0, 0));
		System.out.println(ll.set(4, 4));
		System.out.println(ll.set(3, 3));
		System.out.println(ll.set(5, 5));
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		System.out.println(ll.insert(9, 99));
		ll.getLength();
		System.out.println(ll.insert(0, 999));
		ll.getLength();
		System.out.println(ll.insert(9, 1000));
//		ll.printList();
		ll.getLength();
		System.out.println(ll.insert(5, 5000));
		ll.getLength();
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		System.out.println("*************final*************");
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		System.out.println(ll.remove(0).value);
		System.out.println(ll.remove(11));
		System.out.println(ll.remove(9).value);
		System.out.println(ll.remove(4).value);
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		ll.reverse();
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		ll.removeLast();
		ll.removeFirst();
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		ll.insert(2, 22);
		ll.insert(5, 1000);
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
		ll.append(5555);
		ll.prepend(999);
		ll.printList();
		ll.getHead();
		ll.getTail();
		ll.getLength();
	}
}
